version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="mongodb+srv://MyMongoDBUser:Abcde@12345@cluster0.odsw4.mongodb.net/?retryWrites=true&w=majority"
    ports:
      - 27017:27017